meta_product_name: "Giotto"
meta_title: "Giotto | Europe's Best Sustainable Home Office Rental Platform"
meta_description: "Rent furniture that's ready for business.Unleash your remote team's potential.
No fixed upfront investments, maximum flexibility, happy and productive team."
meta_image: "Giotto-Social-1.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
